# Generated by Django 3.2 on 2022-06-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0003_auto_20220613_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_count', to='postapi.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_count', to='postapi.post'),
        ),
    ]
