# Generated by Django 3.2 on 2022-06-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0004_auto_20220613_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapi.post'),
        ),
    ]
